[workspace]
members = ["crates/cli", "crates/service", "xtask"]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = ["Eric Le Bihan <eric.le.bihan.dev@free.fr>"]
rust-version = "1.85"

[workspace.dependencies]
artifex-engine = { git = "https://github.com/elebihan/artifex.git", rev = "6870a03" }
rmcp = { version = "0.6.1", features = [
  "macros",
  "schemars",
  "server",
  "transport-io",
  "transport-streamable-http-server",
  "transport-worker",
] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "signal",
] }

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
missing_errors_doc = "allow"
result_large_err = "allow"
